### ISSUE TITLE
Is there a node.js version for the server? 

### ISSUE THREAD

**Issue by AlexXi19** [moonrailgun/i18next-toolkit#1]
If that does not exist yet, I'm glad to work on it!

**Comment by moonrailgun** [comment]
Yeah, if you can submit a node version runtime, i think its very helpful of community

**Comment by AlexXi19** [comment]
I did some research around the tooling. There are already existing packages that do a good job, like: https://github.com/i18next/i18next-fs-backend. If someone wants to perform internationalization, they can simply use the extractor / cli provided by this package, and use the backend to read the translation files. Please let me know if my understanding is correct.

**Comment by moonrailgun** [comment]
Sure, `i18next-toolkit` means provide a out of box toolkit rather than replace existed solution.

we make everything together, and give a **Best Practices**, then developer can focus on their business and not need learn other things

**Comment by moonrailgun** [comment]
I think you already did it, closed.

**Comment by moonrailgun** [comment]
Thanks for your work
