### ISSUE TITLE
How may i use this with a ReactJs project without typescript?

### ISSUE THREAD

**Issue by mrmarufpro** [moonrailgun/i18next-toolkit#4]
I found your toolkit super useful ❤️

I was trying to use this toolkit with a React project without a TypeScript. It seems like `tsconfig.json` is a required file, so I created an empty `tsconfig.json` file even though I'm in a project without TypeScript. 
Also, I have changed the `scanner` config like the following: 
```json
"scanner": {
    "source": "./**/*.jsx",
    ....
  },
```

Running `pnpm translation:scan` giving me the following error:

![Screenshot 2024-11-13 at 6 28 02 PM](https://github.com/user-attachments/assets/3b1f738f-4b72-4b5f-a601-13d7a2c82469)

[Codesandbox](https://codesandbox.io/p/devbox/qhtgr2)

**Comment by moonrailgun** [comment]
ok, thanks for your notify.

scanner is high depend typescript ast parser which will helpful to parse all necessary code snippet.

i think ts parser should also support js/jsx but need some config. maybe you can try to add allowJs in your tsconfig.

just like this:

![image](https://github.com/user-attachments/assets/fcf586f9-48f1-4fdb-9a87-6143f4254edd)


-------

but i not know if its can work, just try

**Comment by mrmarufpro** [comment]
it worked for me using `allowJs: true` in tsconfig. Thanks for the help.
